version: "3.2"
services:
 sonarqube:
    build: .
    ports:
      - "9000:9000"
    networks:
      - custom-bridge2
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
 
 ssas:
    build: ssas 
    ports:
      - "8080:8080"
    networks:
      - custom-bridge2
  
networks:
 custom-bridge2:
    external: false       

volumes:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_extensions:
